---
- hosts: all
  tasks:
    - name: Hello World!
      debug:
        msg: "Hello World!"
    - name: Example fail
      ansible.builtin.fail:
        msg: "The system may be stuffed {{ hellome }}"
